tests: add spread test for the maven plugin
canonical/snapcraft pull request #4657
Opened 2024-03-12 22:25 UTC by cmatsuoka

- [x] Have you followed the [guidelines for contributing](https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md)?
- [x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [ ] Have you successfully run `tox run -m lint`?
- [ ] Have you successfully run `tox run -e test-py310`? (supported versions: `py39`, `py310`, `py311`, `py312`)

-----

2024-03-13 11:37 UTC, tigarmo requested changes
Looks good. We should also add a snapcraft-specific example (the one currently in craft-parts)

2024-03-13 11:37 UTC, tigarmo commented on tests/spread/plugins/craft-parts/build-and-run-hello/maven-hello/snap/snapcraft.yaml
> +    command: bin/java -jar $SNAP/jar/hello-$SNAPCRAFT_PROJECT_VERSION.jar
```suggestion
    command: bin/java -jar $SNAP/jar/hello-$CRAFT_PROJECT_VERSION.jar
```

2024-03-13 19:20 UTC, syu-w approved these changes

2024-03-13 20:55 UTC, mattculler approved these changes

2024-03-14 11:30 UTC, tigarmo reviewed
The build is failing because that `/common/craft-parts/mave_plugin.rst` shared doc doesn't exist on that version of craft-parts. We should use the dev branch just to ensure the build is successful

2024-03-14 15:34 UTC, cmatsuoka commented on requirements-devel.txt
> +craft-parts @ git+https://github.com/canonical/craft-parts@CRAFT-2584-Document-maven-plugin
Revert before landing.

2024-03-15 20:03 UTC, tigarmo approved these changes
thanks!

2024-03-18 15:33 UTC, mattculler approved these changes

2024-03-18 19:31 UTC, sergiusens commented
tests are broken

2024-03-21 18:37 UTC, merged