tests: clean up fifos
canonical/snapcraft pull request #5163
Opened 2024-12-03 14:32 UTC by mr-cal

- [x] Have you followed the [guidelines for contributing](https://github.com/canonical/snapcraft/blob/main/CONTRIBUTING.md)?
- [x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [x] Have you successfully run `tox run -m lint`?
- [x] Have you successfully run `tox run -e test-py310`? (supported versions: `py39`, `py310`, `py311`, `py312`)

-----

Fifos get cached in `.tox/` when running tests and then cause the snapcraft snap to fail to build when snapcraft tries to copy the fifo.

source: @sergio-costas via https://chat.canonical.com/canonical/pl/6jpni1n98ifc3fph9ywmdus4iy

2024-12-03 15:20 UTC, mr-cal commented
> I manually deleted the FIFOs inside the .tox folder, as this patch does, and it solved the problem. I re-run the TOX tests and building the snap failed again. I deleted again the FIFOs, added this patch, re-run the TOX tests, and tried again to build the snap, and this time it worked as expected. So this patch fixes the problem.

Thanks for testing!!

2024-12-03 17:34 UTC, bepri approved these changes
Thanks!

2024-12-04 01:15 UTC, lengau requested changes

2024-12-04 01:15 UTC, lengau commented on tests/legacy/unit/test_elf.py
> +        os.unlink(fifo_path)
```suggestion
        try:
            elf_files = elf.get_elf_files(self.fake_elf.root_path, {"fifo"})
            self.assertThat(elf_files, Equals(set()))
        finally:
            os.unlink(fifo_path)
```

2024-12-04 01:15 UTC, lengau commented on tests/unit/elf/test_elf_utils.py
> +        os.unlink(fifo_path)
```suggestion
        try:
            elf_files = elf_utils.get_elf_files_from_list(new_dir, {"fifo"})
            assert elf_files == []
        finally:
            os.unlink(fifo_path)
```

2024-12-04 13:47 UTC, mr-cal commented on tests/legacy/unit/test_elf.py
> +        os.unlink(fifo_path)
oop thanks!

2024-12-05 22:05 UTC, lengau approved these changes
🚀

2024-12-06 18:36 UTC, merged